import pytest
from mycode.main import Person


def test_person_no_param():
    person = Person()
    assert person.name is None
    assert person.email is None


def test_person_with_param(person_data):
    person = Person(person_data["name"], person_data["email"])
    assert person.name == person_data["name"]
    assert person.email == person_data["email"]


def test_person_with_kwparam(person_data):
    person = Person(email=person_data["email"], name=person_data["name"])
    assert person.name == person_data["name"]
    assert person.email == person_data["email"]


def test_person_repr(person_data):
    email = person_data["email"]
    name = person_data["name"]
    person = Person(name, email)
    assert str(person) == f"My name is {name} and my email is {email}"


def test_person_ask_user(monkeypatch):
    data = ["Tim", "tla@rasmil.dk"]
    inputs = iter(data.copy())
    monkeypatch.setattr("builtins.input", lambda _: next(inputs))
    person = Person.ask_user()
    assert person.name == data[0]
    assert person.email == data[1]


def test_disable_input_calls():
    """Test that input gives an RuntimeError generated by
    the autouse fixture in conftest.py"""
    with pytest.raises(RuntimeError) as e:
        person = Person.ask_user()
        assert person is None
        assert e.message == "User inputs not allowed during testing!"
